name: Miniconda package

on: [push]

jobs:
  f2py-test:
    defaults:
      run:
        shell: bash -el {0}

    name: f2py-test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["2"]
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
      - name: f2py workaround
        run: |
          python -c "import sys; print('python:', sys.version)"
          python -c "import numpy; print('numpy:', numpy.__version__)"
          python -m numpy.f2py -v

          ff=`python -c "import numpy.f2py; print(numpy.f2py.__file__)"`
          mbt=`dirname $ff`/_backends/meson.build.template
          mv "$mbt" "$mbt".orig
          cp "$mbt".orig "$mbt"
          sed -e "/import('python').find_installation(/s/'\${python}', //" -i -- "$mbt"
          diff -w -u "$mbt".orig "$mbt" || true
      - name: Test f2py
        run: |
          python -c "import sys; print('python:', sys.version)"
          python -c "import numpy; print('numpy:', numpy.__version__)"
          echo 'f2py:'
          python -m numpy.f2py -v
          echo 'meson:'
          meson -v
          echo 'ninja:'
          ninja --version
           
          bbdir=my-bbdir
          python -m numpy.f2py --verbose -c fib1.f -m fib1 --build-dir $bbdir || true 
          echo "=============="
          ls -laR $bbdir || true
          echo "============== $bbdir/bbdir/meson-logs/meson-log.txt ===="
          cat $bbdir/bbdir/meson-logs/meson-log.txt || true
          echo "=============="
          python -c 'if 1:
            import fib1
            import numpy as np
            a=np.zeros(8,"d")
            fib1.fib(a)
            print(a)
            '
